# Use the official Node.js image
FROM node:14

# Set the working directory
WORKDIR usr/src/app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --silent

# Copy the project files
COPY . ./

# Expose the necessary port
EXPOSE 3000

# Run the React development server
CMD ["npm", "start"]