# Generated by Django 5.1 on 2024-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
